# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prueba.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(465, 193)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AceptarButton = QtWidgets.QPushButton(self.centralwidget)
        self.AceptarButton.setGeometry(QtCore.QRect(130, 110, 75, 23))
        self.AceptarButton.setObjectName("AceptarButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 40, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 60, 47, 13))
        self.label_3.setObjectName("label_3")
        self.Num1TextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.Num1TextEdit.setGeometry(QtCore.QRect(120, 40, 113, 20))
        self.Num1TextEdit.setObjectName("Num1TextEdit")
        self.Num2TextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.Num2TextEdit.setGeometry(QtCore.QRect(120, 75, 113, 20))
        self.Num2TextEdit.setObjectName("Num2TextEdit")
        self.ResultadoplainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ResultadoplainTextEdit.setGeometry(QtCore.QRect(330, 50, 81, 31))
        self.ResultadoplainTextEdit.setObjectName("ResultadoplainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 465, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Interfaz Prueba"))
        self.AceptarButton.setText(_translate("MainWindow", "Ingresar"))
        self.label.setText(_translate("MainWindow", "Numero 1"))
        self.label_2.setText(_translate("MainWindow", "Numero 2"))
        self.label_3.setText(_translate("MainWindow", "Resultado"))



